<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\StockMovement;
use App\Models\Product;
use App\Models\Warehouse;
use App\Models\User;
use App\Models\Inventory;

class StockMovementSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Ensure we have a user for the movements
        $user = User::first();
        if (!$user) {
            $user = User::create([
                'name' => 'System Admin',
                'email' => 'admin@warehouse.com',
                'password' => bcrypt('password'),
                'role' => 'admin'
            ]);
        }

        // Get products and warehouses
        $products = Product::all();
        $warehouses = Warehouse::all();

        if ($products->isEmpty() || $warehouses->isEmpty()) {
            $this->command->warn('No products or warehouses found. Please seed them first.');
            return;
        }

        $movementTypes = ['in', 'out', 'adjustment'];
        $reasons = [
            'in' => ['Purchase order receipt', 'Return from customer', 'Transfer from another warehouse', 'Initial stock'],
            'out' => ['Customer order fulfillment', 'Transfer to another warehouse', 'Damaged goods removal', 'Sample taken'],
            'adjustment' => ['Stock count correction', 'Damage adjustment', 'Expiry removal', 'System correction']
        ];

        $this->command->info('Creating stock movements...');

        foreach ($products->take(5) as $product) {
            foreach ($warehouses->take(2) as $warehouse) {
                // Ensure inventory record exists
                $inventory = Inventory::firstOrCreate(
                    [
                        'product_id' => $product->id,
                        'warehouse_id' => $warehouse->id
                    ],
                    [
                        'quantity' => 0,
                        'reserved_quantity' => 0,
                        'average_cost' => 0
                    ]
                );

                $currentQuantity = $inventory->quantity;

                // Create 3-5 movements per product-warehouse combination
                $movementCount = rand(3, 5);
                
                for ($i = 0; $i < $movementCount; $i++) {
                    $type = $movementTypes[array_rand($movementTypes)];
                    
                    // Adjust logic based on movement type
                    if ($type === 'in') {
                        $quantity = rand(10, 100);
                        $movementQuantity = $quantity;
                    } elseif ($type === 'out') {
                        if ($currentQuantity <= 0) {
                            continue; // Skip if no stock available
                        }
                        $quantity = rand(1, min(20, $currentQuantity));
                        $movementQuantity = -$quantity;
                    } else { // adjustment
                        $adjustment = rand(-10, 20);
                        if ($currentQuantity + $adjustment < 0) {
                            $adjustment = -$currentQuantity; // Don't go below 0
                        }
                        $movementQuantity = $adjustment;
                    }

                    $quantityBefore = $currentQuantity;
                    $quantityAfter = $currentQuantity + $movementQuantity;
                    $currentQuantity = $quantityAfter;

                    // Create the stock movement
                    StockMovement::create([
                        'product_id' => $product->id,
                        'warehouse_id' => $warehouse->id,
                        'user_id' => $user->id,
                        'type' => $type,
                        'quantity' => $movementQuantity,
                        'quantity_before' => $quantityBefore,
                        'quantity_after' => $quantityAfter,
                        'unit_cost' => $type === 'in' ? rand(1000, 10000) / 100 : null,
                        'reference_number' => $this->generateReferenceNumber($type),
                        'reason' => $reasons[$type][array_rand($reasons[$type])],
                        'notes' => 'Generated by seeder for demonstration purposes',
                        'movement_date' => now()->subDays(rand(0, 90))->subHours(rand(0, 23))->subMinutes(rand(0, 59))
                    ]);

                    // Update inventory
                    $inventory->update([
                        'quantity' => $quantityAfter,
                        'average_cost' => $type === 'in' && $movementQuantity > 0 
                            ? $this->calculateAverageCost($inventory, $movementQuantity, rand(1000, 10000) / 100)
                            : $inventory->average_cost,
                        'last_movement_at' => now()
                    ]);
                }
            }
        }

        $totalMovements = StockMovement::count();
        $this->command->info("Created {$totalMovements} stock movements successfully!");
    }

    /**
     * Generate reference number based on movement type
     */
    private function generateReferenceNumber(string $type): string
    {
        $prefixes = [
            'in' => 'PO',
            'out' => 'SO',
            'adjustment' => 'ADJ'
        ];

        $prefix = $prefixes[$type] ?? 'REF';
        return $prefix . '-' . str_pad(rand(1, 9999), 4, '0', STR_PAD_LEFT);
    }

    /**
     * Calculate weighted average cost
     */
    private function calculateAverageCost(Inventory $inventory, int $newQuantity, float $newCost): float
    {
        $currentValue = $inventory->quantity * $inventory->average_cost;
        $newValue = $newQuantity * $newCost;
        $totalQuantity = $inventory->quantity + $newQuantity;

        return $totalQuantity > 0 ? ($currentValue + $newValue) / $totalQuantity : 0;
    }
}